# Generated by Django 3.0.6 on 2020-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_product_limit', models.PositiveIntegerField(blank=True, default=30)),
                ('alert_product_limit', models.PositiveIntegerField(blank=True, default=5)),
                ('system_sound', models.BooleanField(default=True)),
                ('add_cart_product_count_0', models.BooleanField(default=False)),
            ],
        ),
    ]
