# Generated by Django 3.0.6 on 2020-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='color_product_limit',
            field=models.BooleanField(default=True, verbose_name='Oz qolgan tovarlar rang bilan ajratilsin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='add_cart_product_count_0',
            field=models.BooleanField(default=False, verbose_name="Savatchaga qo'shish (Product 0 dona)"),
        ),
        migrations.AlterField(
            model_name='settings',
            name='alert_product_limit',
            field=models.PositiveIntegerField(blank=True, default=5, verbose_name='Ogoxlantirish (Kam qolgan tovar)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='page_product_limit',
            field=models.PositiveIntegerField(blank=True, default=30, verbose_name='Tovar soni(1 page)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='system_sound',
            field=models.BooleanField(default=True, verbose_name='Sound'),
        ),
    ]
