# Generated by Django 3.0.6 on 2020-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200715_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nomi')),
                ('adres', models.CharField(max_length=350, verbose_name='Manzili')),
                ('contract_number', models.CharField(blank=True, max_length=45, verbose_name='Shartnoma raqami')),
                ('inn_number', models.CharField(blank=True, max_length=35, verbose_name='IIN')),
                ('reg_code', models.CharField(blank=True, max_length=35, verbose_name='Registratsiya kodi')),
                ('director', models.CharField(blank=True, max_length=45, verbose_name='Direktor')),
                ('counter', models.CharField(blank=True, max_length=45, verbose_name='Xisobchi')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
