# Generated by Django 3.0.6 on 2020-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefon'),
        ),
    ]
