# Generated by Django 3.0.6 on 2020-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200717_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='add_products_for_one_provider_at_one_day_with_one_list',
            field=models.BooleanField(default=True, verbose_name='1kun ich. 1ta provider'),
        ),
        migrations.AddField(
            model_name='settings',
            name='view_products_check_no',
            field=models.BooleanField(default=True, verbose_name="Tekshirilmagan tovarlar ko'rsatilsin"),
        ),
        migrations.AddField(
            model_name='settings',
            name='view_products_count_no',
            field=models.BooleanField(default=True, verbose_name="Omborda tugagan tovarlar ko'rsatilsin"),
        ),
    ]
