# Generated by Django 3.0.6 on 2020-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200718_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bot_auto_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='bot_auto_send_product_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='bot_auto_send_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='bot_send_add_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='bot_send_order_list',
            field=models.BooleanField(default=True),
        ),
    ]
