# Generated by Django 3.0.6 on 2020-06-28 13:18

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
                ('image', models.FileField(blank=True, upload_to=books.models.image_folder, verbose_name='Foto Shart emas...')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('adres', models.CharField(max_length=50, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqam')),
                ('director', models.CharField(blank=True, max_length=50, verbose_name='Direktor')),
                ('staff', models.CharField(blank=True, max_length=50, verbose_name='Xodim')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Shartnoma raqami')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='IIN raqami')),
                ('reg_code', models.CharField(blank=True, max_length=50, verbose_name='Registratsiya kodi')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=25, verbose_name='Lavozim')),
                ('name', models.CharField(max_length=25, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=25, verbose_name='Familyasi')),
                ('adres', models.CharField(blank=True, max_length=355)),
                ('info', models.TextField(blank=True, max_length=555)),
                ('email', models.CharField(blank=True, max_length=55)),
                ('phone', models.CharField(max_length=16)),
                ('reg', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='SubKategoriya nomi *')),
                ('image', models.FileField(blank=True, upload_to=books.models.image_folder, verbose_name='Foto Shart emas...')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='Kategoriya *')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tovar nomi')),
                ('author', models.CharField(blank=True, max_length=80, verbose_name='Muallif')),
                ('edition', models.CharField(blank=True, max_length=80, verbose_name='Nashriyot')),
                ('description', models.TextField(blank=True, max_length=350, verbose_name='Tovar haqida')),
                ('image', models.ImageField(blank=True, upload_to=books.models.image_folder, verbose_name='Foto Shart emas...')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('count_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sotilishlar soni')),
                ('pur_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Olingan narxi')),
                ('cur_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sotiladigan narxi')),
                ('active', models.BooleanField(default=True)),
                ('check', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to='books.UserAccount', verbose_name="Qo'shdi")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='Kategoriyasi')),
                ('check_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_by', to='books.UserAccount', verbose_name='Tekshirdi')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Provider', verbose_name='Yetqazib beruvchi')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.SubCategory', verbose_name='SubKategoriya ')),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
        migrations.CreateModel(
            name='AddProductArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.UserAccount', verbose_name="Qo'shdi")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Product', verbose_name='Tovar')),
            ],
        ),
    ]
