# Generated by Django 3.0.6 on 2020-07-03 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductarchive',
            name='edition',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nashriyot'),
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='provider',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='books.Provider', verbose_name='Yetqazib beruvchi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni'),
        ),
    ]
