# Generated by Django 3.0.6 on 2020-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200703_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Tovar', 'verbose_name_plural': 'Tovarlar'},
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, max_length=12, verbose_name='Sana'),
        ),
    ]
