# Generated by Django 3.0.6 on 2020-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200703_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month',
            field=models.CharField(blank=True, max_length=15, verbose_name='Oy'),
        ),
    ]
