# Generated by Django 3.0.6 on 2020-07-14 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'Savatcha', 'verbose_name_plural': 'Savatchalar'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id'], 'verbose_name': 'Savatchadagi tovar', 'verbose_name_plural': 'Savatchadagi tovarlar'},
        ),
        migrations.AddField(
            model_name='cart',
            name='all_qty',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Umumiy tovarlar soni'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Umumiy summa'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Umumiy narxi'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Product', verbose_name='Tovar'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni'),
        ),
    ]
