# Generated by Django 3.0.6 on 2020-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200714_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Narxi'),
        ),
    ]
