# Generated by Django 3.0.6 on 2020-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_qty',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Umumiy tovarlar soni'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy summa'),
        ),
    ]
