# Generated by Django 3.0.6 on 2020-07-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200714_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=350, verbose_name="Kalit so'z")),
                ('date', models.CharField(max_length=50, verbose_name='Sana')),
                ('qty', models.PositiveIntegerField(blank=True, default=0, verbose_name='Soni')),
                ('summa', models.PositiveIntegerField(blank=True, default=0, verbose_name='Summa')),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.UserAccount', verbose_name="Mas'ul")),
            ],
        ),
    ]
