# Generated by Django 3.0.6 on 2020-07-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200717_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword', to='books.KeyWord', verbose_name="Kalit so'z"),
        ),
    ]
