# Generated by Django 3.0.6 on 2020-07-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200717_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproductarchive',
            old_name='added_by',
            new_name='check_by',
        ),
        migrations.RemoveField(
            model_name='addproductarchive',
            name='edition',
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='date',
            field=models.CharField(blank=True, max_length=12, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='summa',
            field=models.PositiveIntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.RemoveField(
            model_name='addproductarchive',
            name='product',
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='product',
            field=models.ManyToManyField(blank=True, to='books.Product'),
        ),
        migrations.AlterField(
            model_name='addproductarchive',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Provider', verbose_name='Yetqazib beruvchi'),
        ),
        migrations.AlterField(
            model_name='addproductarchive',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Soni'),
        ),
    ]
