# Generated by Django 3.0.6 on 2020-07-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Position'),
        ),
    ]
