# Generated by Django 3.0.6 on 2020-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200717_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproductarchive',
            name='date',
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='day',
            field=models.PositiveIntegerField(default=0, verbose_name='kun'),
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='month',
            field=models.CharField(blank=True, max_length=12, verbose_name='Oy'),
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Yil'),
        ),
    ]
