# Generated by Django 3.0.6 on 2020-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200717_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductarchive',
            name='day',
            field=models.PositiveIntegerField(default=0, verbose_name='Kun'),
        ),
    ]
