# Generated by Django 3.0.6 on 2020-07-18 11:22

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200718_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addproductarchive',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='pdf',
            field=models.FileField(blank=True, upload_to=books.models.pdf_uploader),
        ),
    ]
