# Generated by Django 3.0.6 on 2020-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200718_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductarchive',
            name='save_as_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addproductarchive',
            name='send_bot',
            field=models.BooleanField(default=False),
        ),
    ]
