# Generated by Django 3.0.6 on 2020-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200718_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
